networks:
  mail_network:
    name: mail_network
    external: false
  traefik:
    name: traefik_proxy
    external: true

volumes:
  postfix-spool:
    driver: local

services:
  mailserver:
    platform: linux/arm64/v8
    build:
      dockerfile: Dockerfile
    container_name: mailserver
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}                    # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.mailserver-secure.entrypoints=websecure"
      - "traefik.http.routers.mailserver-secure.rule=Host(`spam.${MAILSERVER_DOMAIN}`)"
      - "traefik.http.routers.mailserver-secure.service=mailserver-secure"
      - "traefik.http.routers.mailserver-secure.tls.certresolver=leMailResolver"
      - "traefik.http.services.mailserver-secure.loadbalancer.server.port=11334"
      - "traefik.http.services.mailserver-secure.loadbalancer.server.scheme=http"


      - "traefik.http.routers.mail-domain-two.tls=true"
      - "traefik.http.routers.mail-domain-two.tls.certresolver=leMailResolver"
      - "traefik.http.routers.mail-domain-two.rule=Host(`mail.domain-two.com`)"
      - "traefik.http.routers.mail-domain-two.service=mailserver-domain-secure"


      - "traefik.http.routers.mail-domain-three.tls=true"
      - "traefik.http.routers.mail-domain-three.tls.certresolver=leMailResolver"
      - "traefik.http.routers.mail-domain-three.rule=Host(`mail.domain-three.com`)"
      - "traefik.http.routers.mail-domain-three.service=mailserver-domain-secure"


      - "traefik.http.routers.mail-domain-four.tls=true"
      - "traefik.http.routers.mail-domain-four.tls.certresolver=leMailResolver"
      - "traefik.http.routers.mail-domain-four.rule=Host(`mail.domain-four.com`)"
      - "traefik.http.routers.mail-domain-four.service=mailserver-domain-secure"

      - "traefik.http.routers.mail-example-domain.tls=true"
      - "traefik.http.routers.mail-example-domain.tls.certresolver=leMailResolver"
      - "traefik.http.routers.mail-example-domain.tls.domains[0].main=mail.${MAILSERVER_DOMAIN}"
      - "traefik.http.routers.mail-example-domain.tls.domains[0].sans=mail.domain-two.com,mail.domain-three.com,mail.domain-four.com"
      - "traefik.http.routers.mail-example-domain.rule=Host(`mail.example-domain.com`)"
      - "traefik.http.routers.mail-example-domain.service=mailserver-domain-secure"
      - "traefik.http.services.mailserver-domain-secure.loadbalancer.server.port=465"



    ports:
      - "${DEV_ENV:-}25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "${DEV_ENV:-}143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "${DEV_ENV:-}465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "${DEV_ENV:-}587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "${DEV_ENV:-}993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
    # - "31995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
      # - "21082:11334" # expose spam interface
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}       # MariaDB database password (required)
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}     # Rspamd WebUI password (required)
      - ADD_DOMAINS=mail.example-domain.com,mail.domain-two.com,domain-three.com,domain-four.com
    # - DEBUG_MODE=true                        # Enable Postfix, Dovecot, Rspamd and Unbound verbose logging
    # - ENABLE_POP3=true                       # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true                  # Enable fetchmail forwarding
    # - DISABLE_RATELIMITING=false             # Enable ratelimiting policy
    # - DISABLE_CLAMAV=true                    # Disable virus scanning
    # - DISABLE_SIGNING=true                   # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true               # Disable greylisting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
      - ${TRAEFIK_ROOT_PATH}/letsencrypt/le-acme.json:/etc/letsencrypt/acme/acme.json:ro
      - postfix-spool:/var/mail/postfix/spool
    depends_on:
      - mariadb
      - redis
    networks:
      - mail_network
      - traefik

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    platform: linux/arm64/v8
    build:
      context: ./postfix
    container_name: postfixadmin
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.postfixadmin-secure.entrypoints=websecure"
      - "traefik.http.routers.postfixadmin-secure.rule=Host(`postfixadmin.${MAILSERVER_DOMAIN}`)"
      - "traefik.http.routers.postfixadmin-secure.tls.certresolver=leMailResolver"
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - traefik

  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    platform: linux/arm64/v8
    build:
      context: ./rainloop
    container_name: rainloop
    restart: ${RESTART_MODE}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.rainloop-secure.entrypoints=websecure"
      - "traefik.http.routers.rainloop-secure.rule=Host(`webmail.${MAILSERVER_DOMAIN}`)"
      - "traefik.http.routers.rainloop-secure.tls.certresolver=leMailResolver"
    volumes:
      - ${VOLUMES_ROOT_PATH}/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - traefik

  # Database
  # https://github.com/docker-library/mariadb
  # https://mariadb.org/
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    restart: ${RESTART_MODE}
    # Info : These variables are ignored when the volume already exists (if databases was created before).
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
    volumes:
      - ${VOLUMES_ROOT_PATH}/mysql/db:/var/lib/mysql
    networks:
      - mail_network

  # Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:4.0-alpine
    container_name: redis
    restart: ${RESTART_MODE}
    command: redis-server --appendonly yes
    volumes:
      - ${VOLUMES_ROOT_PATH}/redis/db:/data
    networks:
      - mail_network
  # Certdumper
  # https://hub.docker.com/r/humenius/traefik-certs-dumper
  certdumper:
    platform: linux/amd64
    container_name: certdumper
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    command: --restart-containers mailserver,postfixadmin,rainloop
    network_mode: none
    volumes:
      - ${TRAEFIK_ROOT_PATH}/letsencrypt/le-acme.json:/traefik/acme.json:ro
      - ${TRAEFIK_ROOT_PATH}/letsencrypt/dump:/output:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOMAIN: mail.domain-two.com,mail.domain-three.com,mail.domain-four.com
